# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ksk 0.3.2 ruby lib

Gem::Specification.new do |s|
  s.name = "ksk"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Anton Pawlik"]
  s.date = "2014-07-02"
  s.description = "Fast and friendly"
  s.email = "anton.pawlik@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/ksk/application.js",
    "app/assets/javascripts/ksk/classes/NaviAdmin.js",
    "app/assets/stylesheets/ksk/application.css.sass",
    "app/controllers/ksk/navigations_controller.rb",
    "app/helpers/ksk/frontend_helper.rb",
    "app/models/concerns/ksk/asset.rb",
    "app/models/concerns/ksk/category.rb",
    "app/models/concerns/ksk/markdown.rb",
    "app/models/concerns/ksk/navigation.rb",
    "app/models/concerns/ksk/navigation_type.rb",
    "app/models/concerns/ksk/post.rb",
    "app/models/concerns/ksk/preview.rb",
    "app/models/concerns/ksk/static.rb",
    "app/views/bhf/form/column/_crop_thumbs.html.haml",
    "app/views/bhf/form/column/_file.html.haml",
    "app/views/bhf/form/column/_select_file_assets.html.haml",
    "app/views/bhf/form/has_many/_assets.html.haml",
    "app/views/bhf/form/has_many/_upload.html.haml",
    "app/views/bhf/form/has_one/_asset.html.haml",
    "app/views/bhf/platform/_navi.html.haml",
    "app/views/bhf/table/column/_extern_link.haml",
    "config/locales/de.yml",
    "config/locales/en.yml",
    "config/routes.rb",
    "ksk.gemspec",
    "lib/ksk.rb",
    "lib/paperclip_processors/ksk_crop.rb"
  ]
  s.homepage = "http://github.com/antpaw/ksk"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "CMS for bhf"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bhf>, ["~> 0.8"])
      s.add_runtime_dependency(%q<stringex>, ["~> 2.5"])
      s.add_runtime_dependency(%q<paperclip>, ["~> 4.0"])
      s.add_development_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.8"])
    else
      s.add_dependency(%q<bhf>, ["~> 0.8"])
      s.add_dependency(%q<stringex>, ["~> 2.5"])
      s.add_dependency(%q<paperclip>, ["~> 4.0"])
      s.add_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<bhf>, ["~> 0.8"])
    s.add_dependency(%q<stringex>, ["~> 2.5"])
    s.add_dependency(%q<paperclip>, ["~> 4.0"])
    s.add_dependency(%q<shoulda>, ["~> 3.5"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.8"])
  end
end

